### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jduckles** [data-lessons/NEON-R-Spatial-Vector#106]
This repo needs a license file @lwasser.

**Comment by lwasser** [comment]
Hey @jduckles does this look right?

cbd1fc53d551bf17bba09642a840cbec1271721b

This repo doesn't have the DC template either. I'm not sure the best way to go about merging raster and vector & applying the DC template. 

@jsta @tracykteal thoughts?

**Comment by jduckles** [comment]
It is consistent with other Data Carpentry lessons. At Software Carpentry we use CC-BY 4.0 International, but I suspect the license you're linking to is similarly sufficient.

**Comment by lwasser** [comment]
Ok -- @tracykteal should we use the same license that @jduckles mentioned above - CC-BY 4.0? I will update all repos once i'm sure i have the right file. 

Also @jduckles can i use this language on our earth lab repo? We are developing a suite of classroom lessons and i'd like to follow your model if it's ok to steal the language which is very well crafted. THANK YOU!

**Comment by jduckles** [comment]
Absolutely, please do. It makes the world a better place when people can share and remix educational material.

**Comment by lwasser** [comment]
THANK YOU - perfect. I'll add this to our materials as well.Plus the world should always be made better!

I'll wait on @tracykteal to confirm the license link / CC-BY 4.0 vs 3.0. If she is super busy i'll use 3.0 to be consistent until she ok's version 4.0! 👍

**Comment by tracykteal** [comment]
Yes CC-BY 4.0 is the one to use! 

Ideally these lessons would use the new SWC template. https://github.com/swcarpentry/lesson-example/  We're switching the other DC lessons over to this one. Do you think this will work for this lesson? I know we've had some divergence on templating, so we can figure out what will work.

**Comment by lwasser** [comment]
thanks @tracykteal  i'll change it to 4.0

Re the template - i think that is ok as the lessons on NEON's site are now different from ours. not significant but changes are happening independently. i have been going through commits to try to align but i think they will diverge soon anyway because I'd like to restructure as we've talked about doing the entire set of lessons and incorporate a bunch of edits. I wondered if we can just make sure we attribute NEON for building the foundation of these lessons. that should suffice!

The template above is SWC. Is there a DC version I could use?

**Comment by lwasser** [comment]
closing this as we are deprecating this repo but also this was added to the repo!
