### ISSUE TITLE
Lesson 00: About Vector Data section

### ISSUE THREAD

**Issue by snewman29** [data-lessons/NEON-R-Spatial-Vector#14]
About Vector Data section has a note to: INSERT GRAPHIC HERE

Could be helpful to the learners to define the functions and packages that are used in the lesson so they know what they mean. For example the rgdal library is the “R Geospatial Data Abstraction Library” or the readOGR function means read ??? - even with a lot of googling, I couldn’t figure out what OGR refers to.

**Comment by mjones01** [comment]
My comments from this & following section: 
_Importing shapefiles_  Lines ~156
- Want to add what OGR is (stands for) when introducing readOGR, but can’t find what it does stand for. An OGR file but what is that: Open Geospatial …?
  -Why use readOGR, not readShapePoint, etc?  Is it because we want to load files with different types of vector data and the others don’t do that?
- Why aoi in aoiBoundary file name? What does it mean why isn't object just Boundaries since the others are Lines & Point.  

I'm happy to make the edits but someone needs to provide me with the answers.  Thanks.

**Comment by jsta** [comment]
Have a look at this FAQ: [https://trac.osgeo.org/gdal/wiki/FAQ](https://trac.osgeo.org/gdal/wiki/FAQ)

Specifically, [https://trac.osgeo.org/gdal/wiki/FAQGeneral#WhatdoesOGRstandfor](https://trac.osgeo.org/gdal/wiki/FAQGeneral#WhatdoesOGRstandfor)

I assumed that aoi stands for "area of interest".

**Comment by lwasser** [comment]
yup - AOI - area of interest. it's a common term in GIS world but probably worth defining as it might not be common everywhere!

The graphic - let's leave that note that because colin will make the graphic. i'll remind him on thursday!

**Comment by mjones01** [comment]
Fixed.  Thanks for the info.  Issue can be closed.

**Comment by lwasser** [comment]
@mjones01 this is where you might say fixed - and then reference a PR where it was actually fixed so we can track the change. So how about you submit a PR, then reference it here. Then i'll close the issue? sound ok?

**Comment by mjones01** [comment]
Pull request #50.

**Comment by snewman29** [comment]
Thanks for the links to what readOGR stands for @jsta - that was driving me crazy!
