### ISSUE TITLE
Lesson 02: Create a new Shapefile from a Spatial Object section

### ISSUE THREAD

**Issue by snewman29** [data-lessons/NEON-R-Spatial-Vector#31]
Should the following say “directory” rather than “director” ?
--the director where we want to save our shapefile

I think something is wrong with the code rendering box in this section - the code just appears on the web page instead of in a black box like the other code.

Side note: I noticed that shorthand is often used when describing different elements. For example, in the text and headers, CRS is often used instead of spelling out Coordinate Reference System. I wonder if it might be worth spelling out CRS more often so that when people are searching for R tutorials about coordinate reference systems, these tutorials come up more often. Just a thought!

**Comment by mjones01** [comment]
Director- fixed
Code section - fixed.  It seems like we can have both a code section title and a separate echo=FALSE or other command.  
In last pull request I did update many of the CRS to Coordinate Reference System (at least once per larger section).  In future readings let's see if this is enough.

**Comment by lwasser** [comment]
OK -- should we start a new issue that has to deal with acronyms throughout?

**Comment by mjones01** [comment]
I'm going to review all the lessons again as soon as they are re-knit.  If I think acronyms are still an issue I'll post the issue.

**Comment by lwasser** [comment]
ok i see an issue here: 

```
Create a New Shapefile from A Spatial Object

We can write an R spatial object to a shapefile using the writeOGR function in rgdal. To do this we need the following arguments

    the name of the spatial object (plot.locationSp)
    the directory where we want to save our shapefile (to use current = getwd() or you can specify a different path)
    the name of the new shapefile (newFile)

    the driver which specifies the file format (ESRI Shapefile)

    #write a shapefile writeOGR(plot.locationSp, getwd(), “newFile”, driver=”ESRI Shapefile”)

    ## Error in writeOGR(plot.locationSp, getwd(), “newFile”, driver = “ESRI Shapefile”): layer exists, use a new layer name
```

Probably two things happening.
1. Jekyll has a weird bug where you need to have a line of text after a bulleted list. So add a simple line after the last bullet. Then we need to turn off actually running the code because it's trying to overwrite an existing shapefile. 

``````
Let's export the `plot.locationSp` as an `ESRI Shapefile`.

```{r write-shapefile, eval=FALSE }
#code as is currently in the file goes here.
``````

hey @mjones01 let me know if you want to tackle this in your next PR. Then i think we can close this issue!

**Comment by mjones01** [comment]
I think I've already made this change in my current bunch of edits.  I'll send a pull request when I head out of the office.

**Comment by lwasser** [comment]
ok sounds good! i'm signing off. I'll merge it either tonight OR thursday. Have a nice holiday! thank you for all of the hard work, comments feedback @snewman29 @mjones01 !!

**Comment by mjones01** [comment]
I'm confused by the last bit:  
"Then we need to turn off actually running the code because it's trying to overwrite an existing shapefile. Let's export the `plot.locationSp` as an `ESRI Shapefile`.

{r write-shapefile, eval=FALSE }
#code as is currently in the file goes here.

Currently plot.location is a .csv file but it was converted to a spatial R object plot.locationSp  which, unless I'm not understanding and the lesson doesn't explain, isn't a shapefile until we write it as one in this section.   So we would want this section of code to run?  

Please clarify.  I've made all other changes referenced in this issue.  Can close one this last one is addressed.

**Comment by mjones01** [comment]
All of these items have been addressed.  Close?

**Comment by lwasser** [comment]
done.
