### ISSUE TITLE
Lesson 02: Dealing with Spatial Objects in Different CRS’ section

### ISSUE THREAD

**Issue by snewman29** [data-lessons/NEON-R-Spatial-Vector#32]
Remove the extra / after HARV in the following code:
newPlots <- readOGR("boundaryFiles/HARV/","newPlots_latLon")

An error message is appearing in your code box in this section after the lines:
# http://www.statmethods.net/advgraphs/parameters.html
# add these points to our plot

plot(newPlots, add=TRUE, col=115, pch=19)

I love the way you did this part of the lesson so that “nothing happens” - I was looking at my plot thinking I had done something off. Then I read your next section of text and was like “Oh - that’s the point. Now we’re going to learn about projections” :). It was great suspense for me as a learner! Nice!

An error message is appearing in your code box in the section after the code line:
 plot(newPlots_UTMZ18N, add=TRUE, col=116, pch=19)

It would be great to see what the final plot looks like! Adding a graphic here would be awesome :)

**Comment by jsta** [comment]
Thanks for testing this out! However, I am not getting an error when running the code:
`plot(newPlots_UTMZ18N, add=TRUE, col=116, pch=19)`

Must be an error with the website rendering...

**Comment by lwasser** [comment]
Yup -- @jsta what i've discovered recently is that when the add=TRUE happens in separate chunks, R doesn't know what to add the data to. this might be because i'm knitting it remotely. Or it might be because there's text between the chunks. I might see if you place a hidden chunk with the plot code right BEFORE the box if that fixes it. OR if it all needs to be in the same chunk. I'm hoping the  hidden chunk before will fix things! 

good catch @snewman29 and good to know the code works @jsta - it's a knitting issue for sure!

**Comment by lwasser** [comment]
@mjones01 to fix this rendering issue, we need to replot - when you knit the plot chunks don't carry over. So it's looking to add the element to an existing plot that it can't find.

Line 239 - 

``` r project-vectors

#note: read ogr is preferred as it maintains prj info
newPlots <- readOGR("boundaryFiles/HARV", "newPlots_latLon")

#add these points to our plot
plot(newPlots, add=TRUE, col=115, pch=19)

```

The fix: add the following code to the top of the chunk so the entire plot is regenerated in the chunk:

```
plot(plot.locationSp, main="Map of Study Area")

#let's add the polygon & tower point layer to our plot
plot(aoiBoundary, add=TRUE)
plot(point, col="red", add=TRUE)

#add roads to our plot, Lesson00: lines<-readOGR("boundaryFiles/HARV/", "HARV_roads")
plot(lines, add=TRUE)

#add new points to our plot
plot(newPlots, add=TRUE, col=115, pch=19)
```

**Comment by jsta** [comment]
I think you can also specify chunk dependencies using the `dependson` option ([http://yihui.name/knitr/options/](http://yihui.name/knitr/options/)).

**Comment by mjones01** [comment]
@jsta  unfortunately I don't think that option will work as we don't want to cache the chunks (they aren't evaluated if cached) and `dependson` only works for cached chunks.  @jsta or @lwasser let me know if I'm misinterpreting the descriptions of each (excerpts below).  It would be a more elegant solution than replotting in each chunk.  
From http://yihui.name/knitr/options/
On Cached chunks: "when evaluating code chunks, the cached chunks are skipped, but the objects created in these chunks are (lazy-) loaded from previously saved databases (.rdb and .rdx) files,"
On `dependson`:  "this option applies to cached chunks only -- sometimes the objects in a cached chunk may depend on other cached chunks" 

Another option would be to name the final plot output from each chunk and then just carry that between plots?

**Comment by mjones01** [comment]
The solution to this is to create any plot you want to add on to as a object (with a name) so that you can just have the "name+ whatever you are adding to plot" in the next chunk.  Just remember that if you are adding across multiple chunks all the new additions need to be a named object as well to carry over.  As of PR51 all plots should be functional.

**Comment by lwasser** [comment]
woo hoo! thanks! should we close this?

**Comment by mjones01** [comment]
Sure.  I'll add something to the gDoc about this so we don't forget it again.
